# Generated by Django 5.2.7 on 2025-11-17 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Пользователь"),
                            ("manager", "Менеджер"),
                            ("admin", "Администратор"),
                        ],
                        default="user",
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False, verbose_name="Email подтвержден"
                    ),
                ),
                (
                    "blocked",
                    models.BooleanField(default=False, verbose_name="Заблокирован"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "профиль",
                "verbose_name_plural": "профили",
            },
        ),
    ]
